package org.clickframes.clipr.service;

/**
 * different legal outcomes for Upload 
 * 
  * On this page, the user may upload an appspec.
  *
 * Automatically generated by clickframes
 * 
 * @author Vineet Manohar
 */
 public enum UploadUploadFormUploadOutcome {
    /** 
     * Appspec is valid
     */ 
    appspecIsValid, 

    /** 
     * Appspec is invalid
     */ 
    appspecIsInvalid
}
// clickframes::version=4020637315::clickframes
