package org.clickframes.clipr.controller;

import java.io.Serializable;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jboss.seam.annotations.In;


import java.util.List;
import java.util.ArrayList;
import org.richfaces.model.UploadItem;

import org.clickframes.clipr.service.UploadUploadFormUploadOutcome;
import org.clickframes.clipr.service.UploadService;


/**
 * Glue code to bind Upload an appspec Service with the view framework (Seam). This class contains
 * a default implementation of the action methods. Please avoid reimplmenting the action methods in this class.
 * The purpose of this class is to declare properties which can be bound to the UI.
 * 
  * On this page, the user may upload an appspec.
  *
 * Automatically generated by clickframes
 * 
 * @author Vineet Manohar
 */
public abstract class GeneratedUploadController implements Serializable {
	@In("#{uploadService}")
	protected UploadService uploadService;

	@SuppressWarnings("unused")
	private static final Log logger = LogFactory.getLog(GeneratedUploadController.class);







/** Your Appspec
 *
  */
private byte[] uploadFormYourAppspec;

public byte[] getUploadFormYourAppspec() {
return this.uploadFormYourAppspec;
}

public void setUploadFormYourAppspec(byte[] uploadFormYourAppspec) {
this.uploadFormYourAppspec = uploadFormYourAppspec;
}

private String uploadFormYourAppspec_fileName;

public String getUploadFormYourAppspec_fileName() {
return this.uploadFormYourAppspec_fileName;
}

public void setUploadFormYourAppspec_fileName(String uploadFormYourAppspec_fileName) {
this.uploadFormYourAppspec_fileName = uploadFormYourAppspec_fileName;
}

 

/**
 * Upload
 *
  * Automatically generated by clickframes
 */
public abstract UploadUploadFormUploadOutcome uploadFormUpload();


	private static final long serialVersionUID = 1L;
}
// clickframes::version=3419256095::clickframes
